[package]
name = "ps-spsc"
version = "0.5.0"
authors = ["Zachary Tong <zacharyjtong@gmail.com>"]
license = "Apache-2.0"
description = "A bounded SPSC queue"

repository = "https://github.com/pathscale/bounded-spsc-queue"
homepage = "https://github.com/pathscale/bounded-spsc-queue"
documentation = "https://docs.rs/ps-spsc"
keywords = ["data-structures"]
readme = "README.md"



[lib]
name = "spsc"
doctest = false

[[bench]]
name = "benchmark"
harness = false

[dev-dependencies]
criterion = "0.2.3"
time = "0.1.39"
